export const GET_WALLET = "GET_WALLET"
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS"

export const ADD_ASSET = "ADD_ASSET"
export const ADD_ASSET_SUCCESS = "ADD_ASSET_SUCCESS"
export const DELETE_ASSET = "DELETE_ASSET"
export const DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS"
